#database url to connect with  database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/exam}
spring.datasource.username=${DB_USERNAME:exam_user}
spring.datasource.password=${DB_PASSWORD:exam_password}
#Hibernate JPA Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
